### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by mubasherkhan** [leverdeterre/CustomScrollIndicator#5]
`CustomScrollViewIndicator[882:537748] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<JMOViewController 0x15664640> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key scrollView.'`

**Comment by leverdeterre** [comment]
Right ! 
i have reproduce this using ipad simulator.
iPhone simulator is a better choice to test.
I will fix the iPad

**Comment by leverdeterre** [comment]
I have fixed the demo project with my last commit 

https://github.com/leverdeterre/CustomScrollIndicator/commit/e1cb4a95daf6a56d3f5823dbb305f3f0264f0564

**Comment by mubasherkhan** [comment]
Thanks  its working fine now .
